### ISSUE TITLE
Không lưu được thông tin trong mục Admin Control Panel

### ISSUE THREAD

**Issue by Annhiennn** [Belikhun/thi-trac-nghiem#7]
Hi tác giả,
Rất cảm ơn bạn đã tạo ra sản phẩm này.
Hiện tại mình đang thử nghiệm cho các em học sinh làm bài trắc nghiệm.
Mình muốn thay đổi thông tin thi trong Admin Control Panel nhưng các thông số khác mặc định đều báo lỗi như sau:

ERROR OCCURED
Một lỗi không mong muốn đã sảy ra!
[3] >>> HTTP 500: Internal Server Error (POST /api/config)
Stack Trace:
[-1 500] >>> Error Occurred: unserialize(): Error at offset 76 of 76 bytes tại /libs/belibrary.php:811
[8] >>> unserialize(): Error at offset 76 of 76 bytes

Mặc dù mình đã sử dụng phiên bản mới nhất nhưng lỗi không mong muốn vẫn xảy ra. Mong tác giả cho thông tin để sửa lỗi này. 
Xin cảm ơn và trân trọng!

**Comment by Annhiennn** [comment]
Đôi khi nhấn Lưu thì có thông báo hơi khác chút là:
[3] >>> HTTP 500: Internal Server Error (POST /api/config)
Stack Trace:
[-1 500] >>> BLibException: [HTTP 500] [-1]: getConfig(): Không tìm thấy cài đặt time.contest.begin tại /libs/config.php:131
[44 500] >>> Undefined Index: contest tại /libs/belibrary.php:254

**Comment by Belikhun** [comment]
![image](https://github.com/Belikhun/thi-trac-nghiem/assets/19252372/9ce416e6-09f3-4efd-9010-18e4164fa488)
Ở trong thư mục web của hệ thống có một thư mục tên là `.cache`, bạn mở thư mục này và xóa toàn bộ các file có đuôi `.cache` thử xem nhé.

Hoặc bạn có thể dùng luôn nút **Xóa Cache** trong bảng cài đặt
![image](https://github.com/Belikhun/thi-trac-nghiem/assets/19252372/6816b0c2-d30c-48b0-a60a-389489ba99c6)

**Comment by Annhiennn** [comment]
![image](https://github.com/Belikhun/thi-trac-nghiem/assets/33947200/ee5b5188-b7eb-47b1-b1e5-fa50797b168e)
M đã làm theo cả 2 hướng dẫn trên nhưng đều không thành công.

**Comment by Belikhun** [comment]
Bạn mở file `modules/hash.php` và xoá 5 dòng ở hình dưới đây thử xem nhé
<img width="521" alt="Ảnh màn hình 2023-05-11 lúc 14 01 10" src="https://github.com/Belikhun/thi-trac-nghiem/assets/19252372/fca7b591-44f7-402c-a15c-03e0703471e6">

Chi tiết bạn có thể xem commit 3003e66e865d5cafaf49ee729feec22af4852ef0

**Comment by Annhiennn** [comment]
Rất cảm ơn tác giả.
